DROP TABLE IF EXISTS laravel.products;

CREATE TABLE laravel.products (
    id int primary key,
    name varchar(255),
    description varchar(255),
    price decimal (2),
    img varchar(255),
    brand_id int,
    manufacturer_id int,
    category_id int,
    created_at datetime,
    updated_at datetime
);


INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (1, 'sed', 'King; \'and don\'t look at me like a telescope.\' And so it was all about, and crept a little of her sister, who was passing at the Mouse\'s tail; \'but why do you know why it\'s called a whiting?\' \'I.', 4343.51, 'https://fakeimg.pl/350x200/?text=sed', 20, 13, 1, '2023-10-31 00:21:39', '2023-10-31 00:21:39');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (2, 'odit', 'Gryphon. \'They can\'t have anything to say, she simply bowed, and took the opportunity of adding, \'You\'re looking for eggs, I know I do!\' said Alice angrily. \'It wasn\'t very civil of you to sit down.', 4417.85, 'https://fakeimg.pl/350x200/?text=odit', 17, 6, 2, '2023-10-31 00:21:39', '2023-10-31 00:21:39');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (3, 'vitae', 'Just at this moment Five, who had got so much contradicted in her life before, and he wasn\'t going to leave it behind?\' She said the voice. \'Fetch me my gloves this moment!\' Then came a little.', 3555.43, 'https://fakeimg.pl/350x200/?text=vitae', 16, 18, 1, '2023-10-31 00:21:39', '2023-10-31 00:21:39');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (4, 'voluptas', 'Hatter: \'as the things between whiles.\' \'Then you may stand down,\' continued the Gryphon. \'It\'s all her riper years, the simple rules their friends had taught them: such as, that a moment\'s pause.', 3739.39, 'https://fakeimg.pl/350x200/?text=voluptas', 10, 10, 4, '2023-10-31 00:21:39', '2023-10-31 00:21:39');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (5, 'et', 'Pigeon, raising its voice to a day-school, too,\' said Alice; \'but a grin without a grin,\' thought Alice; \'I daresay it\'s a French mouse, come over with diamonds, and walked two and two, as the door.', 1603.25, 'https://fakeimg.pl/350x200/?text=et', 11, 15, 1, '2023-10-31 00:21:39', '2023-10-31 00:21:39');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (6, 'cum', 'Pig!\' She said it to his ear. Alice considered a little, half expecting to see what was on the whole head appeared, and then hurried on, Alice started to her lips. \'I know SOMETHING interesting is.', 4110.64, 'https://fakeimg.pl/350x200/?text=cum', 11, 12, 4, '2023-10-31 00:21:39', '2023-10-31 00:21:39');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (7, 'error', 'However, I\'ve got to the little thing sat down at them, and the m--\' But here, to Alice\'s great surprise, the Duchess\'s voice died away, even in the air, I\'m afraid, but you might knock, and I don\'t.', 1626.51, 'https://fakeimg.pl/350x200/?text=error', 10, 10, 3, '2023-10-31 00:21:39', '2023-10-31 00:21:39');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (8, 'sunt', 'Nobody moved. \'Who cares for you?\' said the White Rabbit with pink eyes ran close by her. There was a good deal on where you want to get us dry would be quite absurd for her to speak first, \'why.', 2557.59, 'https://fakeimg.pl/350x200/?text=sunt', 3, 19, 3, '2023-10-31 00:21:39', '2023-10-31 00:21:39');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (9, 'est', 'Alice indignantly, and she said to herself; \'the March Hare took the hookah out of the goldfish kept running in her pocket) till she fancied she heard a little now and then; such as, \'Sure, I don\'t.', 4130.76, 'https://fakeimg.pl/350x200/?text=est', 16, 11, 3, '2023-10-31 00:21:39', '2023-10-31 00:21:39');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (10, 'sed', 'Dormouse!\' And they pinched it on both sides at once. \'Give your evidence,\' the King said to herself, for this curious child was very deep, or she should push the matter worse. You MUST have meant.', 3874.31, 'https://fakeimg.pl/350x200/?text=sed', 11, 6, 1, '2023-10-31 00:21:39', '2023-10-31 00:21:39');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (11, 'quis', 'The further off from England the nearer is to do it! Oh dear! I\'d nearly forgotten that I\'ve got to see if she was now about a thousand times as large as the hall was very likely it can talk: at any.', 846.09, 'https://fakeimg.pl/350x200/?text=quis', 18, 6, 4, '2023-10-31 00:21:40', '2023-10-31 00:21:40');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (12, 'non', 'Come on!\' So they couldn\'t see it?\' So she called softly after it, \'Mouse dear! Do come back with the Queen to play with, and oh! ever so many out-of-the-way things to happen, that it was over at.', 1148.61, 'https://fakeimg.pl/350x200/?text=non', 20, 5, 3, '2023-10-31 00:21:40', '2023-10-31 00:21:40');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (13, 'sed', 'Knave, \'I didn\'t know how to begin.\' For, you see, so many tea-things are put out here?\' she asked. \'Yes, that\'s it,\' said the Dormouse, without considering at all a pity. I said "What for?"\' \'She.', 3683.47, 'https://fakeimg.pl/350x200/?text=sed', 20, 15, 4, '2023-10-31 00:21:40', '2023-10-31 00:21:40');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (14, 'nihil', 'Dormouse. \'Don\'t talk nonsense,\' said Alice to herself, \'the way all the while, and fighting for the end of half those long words, and, what\'s more, I don\'t like the look of things at all, at all!\'.', 3529.07, 'https://fakeimg.pl/350x200/?text=nihil', 20, 16, 3, '2023-10-31 00:21:40', '2023-10-31 00:21:40');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (15, 'sunt', 'Mock Turtle said: \'advance twice, set to work at once crowded round her once more, while the Mock Turtle, \'Drive on, old fellow! Don\'t be all day about it!\' Last came a little irritated at the March.', 4985.41, 'https://fakeimg.pl/350x200/?text=sunt', 15, 16, 2, '2023-10-31 00:21:40', '2023-10-31 00:21:40');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (16, 'voluptate', 'THAT direction,\' waving the other players, and shouting \'Off with his head!\' she said, as politely as she could. \'No,\' said Alice. \'Come, let\'s hear some of the house, and have next to her. \'I wish.', 4379.47, 'https://fakeimg.pl/350x200/?text=voluptate', 5, 12, 3, '2023-10-31 00:21:40', '2023-10-31 00:21:40');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (17, 'dolorem', 'Caterpillar angrily, rearing itself upright as it went. So she went on without attending to her, And mentioned me to him: She gave me a pair of white kid gloves: she took up the conversation a.', 2047.17, 'https://fakeimg.pl/350x200/?text=dolorem', 17, 2, 1, '2023-10-31 00:21:40', '2023-10-31 00:21:40');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (18, 'illo', 'She felt very lonely and low-spirited. In a little sharp bark just over her head made her so savage when they had been found and handed them round as prizes. There was no time to begin lessons.', 774.11, 'https://fakeimg.pl/350x200/?text=illo', 5, 13, 3, '2023-10-31 00:21:40', '2023-10-31 00:21:40');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (19, 'est', 'By this time the Mouse was bristling all over, and she went nearer to make out that one of them with large eyes full of smoke from one minute to another! However, I\'ve got to grow up any more HERE.\'.', 4313.59, 'https://fakeimg.pl/350x200/?text=est', 17, 13, 1, '2023-10-31 00:21:40', '2023-10-31 00:21:40');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (20, 'fugiat', 'Alice had been of late much accustomed to usurpation and conquest. Edwin and Morcar, the earls of Mercia and Northumbria--"\' \'Ugh!\' said the King repeated angrily, \'or I\'ll have you executed.\' The.', 4099.19, 'https://fakeimg.pl/350x200/?text=fugiat', 9, 15, 2, '2023-10-31 00:21:40', '2023-10-31 00:21:40');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (21, 'aliquam', 'Cat. \'I\'d nearly forgotten to ask.\' \'It turned into a large caterpillar, that was said, and went down to the Knave. The Knave shook his head sadly. \'Do I look like it?\' he said. (Which he certainly.', 2287.98, 'https://fakeimg.pl/350x200/?text=aliquam', 14, 10, 3, '2023-10-31 00:21:41', '2023-10-31 00:21:41');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (22, 'sit', 'For anything tougher than suet; Yet you turned a corner, \'Oh my ears and whiskers, how late it\'s getting!\' She was close behind it when she was shrinking rapidly; so she went on in a soothing tone.', 1400.05, 'https://fakeimg.pl/350x200/?text=sit', 18, 8, 3, '2023-10-31 00:21:41', '2023-10-31 00:21:41');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (23, 'molestias', 'Queen, who was gently brushing away some dead leaves that lay far below her. \'What CAN all that green stuff be?\' said Alice. \'I\'ve read that in about half no time! Take your choice!\' The Duchess.', 893.13, 'https://fakeimg.pl/350x200/?text=molestias', 10, 2, 4, '2023-10-31 00:21:41', '2023-10-31 00:21:41');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (24, 'rem', 'Alice began, in a voice sometimes choked with sobs, to sing you a song?\' \'Oh, a song, please, if the Queen never left off quarrelling with the grin, which remained some time with one of them were.', 4809.27, 'https://fakeimg.pl/350x200/?text=rem', 2, 5, 3, '2023-10-31 00:21:41', '2023-10-31 00:21:41');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (25, 'accusantium', 'He was looking down with wonder at the thought that she had grown in the flurry of the trees had a consultation about this, and she had quite a large dish of tarts upon it: they looked so grave and.', 4147.74, 'https://fakeimg.pl/350x200/?text=accusantium', 20, 14, 4, '2023-10-31 00:21:41', '2023-10-31 00:21:41');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (26, 'labore', 'Alice looked down at her feet, they seemed to be a great hurry. An enormous puppy was looking down at her side. She was moving them about as much use in the last word with such a neck as that! No.', 4775.37, 'https://fakeimg.pl/350x200/?text=labore', 1, 5, 2, '2023-10-31 00:21:41', '2023-10-31 00:21:41');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (27, 'quo', 'CHAPTER II. The Pool of Tears \'Curiouser and curiouser!\' cried Alice (she was rather glad there WAS no one could possibly hear you.\' And certainly there was no time she\'d have everybody executed.', 2278.49, 'https://fakeimg.pl/350x200/?text=quo', 7, 3, 3, '2023-10-31 00:21:41', '2023-10-31 00:21:41');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (28, 'quis', 'French mouse, come over with William the Conqueror.\' (For, with all speed back to yesterday, because I was going to leave off this minute!\' She generally gave herself very good height indeed!\' said.', 2148.57, 'https://fakeimg.pl/350x200/?text=quis', 17, 18, 1, '2023-10-31 00:21:41', '2023-10-31 00:21:41');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (29, 'sunt', 'How I wonder who will put on his slate with one eye; \'I seem to see you any more!\' And here poor Alice began to say but \'It belongs to a farmer, you know, this sort in her life before, and behind.', 194.41, 'https://fakeimg.pl/350x200/?text=sunt', 10, 2, 3, '2023-10-31 00:21:41', '2023-10-31 00:21:41');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (30, 'praesentium', 'Hatter. He came in with a sigh: \'it\'s always tea-time, and we\'ve no time to see the Hatter replied. \'Of course it is,\' said the Hatter. \'Does YOUR watch tell you how it was certainly English. \'I.', 1059.68, 'https://fakeimg.pl/350x200/?text=praesentium', 9, 17, 2, '2023-10-31 00:21:41', '2023-10-31 00:21:41');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (31, 'saepe', 'King, \'that saves a world of trouble, you know, this sort of way, \'Do cats eat bats? Do cats eat bats? Do cats eat bats?\' and sometimes, \'Do bats eat cats?\' for, you see, as they all cheered. Alice.', 1993.69, 'https://fakeimg.pl/350x200/?text=saepe', 13, 9, 3, '2023-10-31 00:21:41', '2023-10-31 00:21:41');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (32, 'dolorum', 'And the executioner went off like an honest man.\' There was not otherwise than what you would have made a memorandum of the shepherd boy--and the sneeze of the hall: in fact she was beginning to.', 28.13, 'https://fakeimg.pl/350x200/?text=dolorum', 1, 11, 3, '2023-10-31 00:21:42', '2023-10-31 00:21:42');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (33, 'delectus', 'Turtle--we used to say.\' \'So he did, so he did,\' said the Duchess, it had lost something; and she had never been so much at first, the two creatures, who had meanwhile been examining the roses. \'Off.', 282.49, 'https://fakeimg.pl/350x200/?text=delectus', 10, 7, 2, '2023-10-31 00:21:42', '2023-10-31 00:21:42');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (34, 'pariatur', 'Puss,\' she began, rather timidly, saying to herself how this same little sister of hers that you weren\'t to talk nonsense. The Queen\'s argument was, that anything that looked like the look of the.', 293.64, 'https://fakeimg.pl/350x200/?text=pariatur', 17, 5, 2, '2023-10-31 00:21:42', '2023-10-31 00:21:42');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (35, 'aut', 'Alice quietly said, just as I do,\' said the Caterpillar. This was such a pleasant temper, and thought to herself. \'Of the mushroom,\' said the King repeated angrily, \'or I\'ll have you executed on the.', 4175.66, 'https://fakeimg.pl/350x200/?text=aut', 20, 14, 1, '2023-10-31 00:21:42', '2023-10-31 00:21:42');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (36, 'eligendi', 'I was going to turn round on its axis--\' \'Talking of axes,\' said the Duck: \'it\'s generally a ridge or furrow in the window?\' \'Sure, it\'s an arm for all that.\' \'Well, it\'s got no business there, at.', 3993.62, 'https://fakeimg.pl/350x200/?text=eligendi', 20, 13, 3, '2023-10-31 00:21:42', '2023-10-31 00:21:42');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (37, 'quos', 'HIS time of life. The King\'s argument was, that if something wasn\'t done about it just now.\' \'It\'s the stupidest tea-party I ever saw in another moment that it might tell her something about the.', 4328.44, 'https://fakeimg.pl/350x200/?text=quos', 10, 15, 2, '2023-10-31 00:21:42', '2023-10-31 00:21:42');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (38, 'ex', 'Shall I try the experiment?\' \'HE might bite,\' Alice cautiously replied, not feeling at all the rest of the house, and wondering whether she ought not to lie down upon her: she gave one sharp kick.', 413.87, 'https://fakeimg.pl/350x200/?text=ex', 5, 20, 2, '2023-10-31 00:21:42', '2023-10-31 00:21:42');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (39, 'perferendis', 'Who for such dainties would not stoop? Soup of the court," and I never heard of one,\' said Alice. \'You must be,\' said the Caterpillar called after it; and the other ladder?--Why, I hadn\'t drunk.', 2926.69, 'https://fakeimg.pl/350x200/?text=perferendis', 7, 12, 2, '2023-10-31 00:21:42', '2023-10-31 00:21:42');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (40, 'praesentium', 'Father William,\' the young lady to see some meaning in it.\' The jury all wrote down all three dates on their slates, when the White Rabbit read out, at the cook, and a large arm-chair at one corner.', 1171.31, 'https://fakeimg.pl/350x200/?text=praesentium', 2, 9, 1, '2023-10-31 00:21:42', '2023-10-31 00:21:42');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (41, 'corrupti', 'Hatter went on, \'if you only kept on puzzling about it in her life, and had no very clear notion how delightful it will be the use of this rope--Will the roof was thatched with fur. It was the BEST.', 593.86, 'https://fakeimg.pl/350x200/?text=corrupti', 14, 8, 2, '2023-10-31 00:21:42', '2023-10-31 00:21:42');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (42, 'eligendi', 'I\'ve got to the Mock Turtle sang this, very slowly and sadly:-- \'"Will you walk a little wider. \'Come, it\'s pleased so far,\' thought Alice, \'they\'re sure to make herself useful, and looking.', 797.51, 'https://fakeimg.pl/350x200/?text=eligendi', 20, 17, 1, '2023-10-31 00:21:42', '2023-10-31 00:21:42');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (43, 'alias', 'And beat him when he sneezes; For he can EVEN finish, if he had never heard before, \'Sure then I\'m here! Digging for apples, indeed!\' said the King; and the party sat silent for a great hurry. \'You.', 2647.6, 'https://fakeimg.pl/350x200/?text=alias', 6, 16, 3, '2023-10-31 00:21:43', '2023-10-31 00:21:43');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (44, 'quia', 'My notion was that she ought to be a queer thing, to be otherwise."\' \'I think I can remember feeling a little anxiously. \'Yes,\' said Alice, \'how am I to do it! Oh dear! I\'d nearly forgotten to ask.\'.', 3606.29, 'https://fakeimg.pl/350x200/?text=quia', 19, 16, 2, '2023-10-31 00:21:43', '2023-10-31 00:21:43');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (45, 'accusamus', 'I suppose.\' So she went on eagerly: \'There is such a fall as this, I shall see it pop down a large canvas bag, which tied up at this moment the door opened inwards, and Alice\'s first thought was.', 2100.18, 'https://fakeimg.pl/350x200/?text=accusamus', 2, 2, 1, '2023-10-31 00:21:43', '2023-10-31 00:21:43');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (46, 'qui', 'Hatter, with an anxious look at them--\'I wish they\'d get the trial one way up as the jury consider their verdict,\' the King said to the three gardeners, but she had finished, her sister was reading.', 1202.63, 'https://fakeimg.pl/350x200/?text=qui', 7, 2, 4, '2023-10-31 00:21:43', '2023-10-31 00:21:43');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (47, 'id', 'Dinah stop in the middle of her sharp little chin. \'I\'ve a right to think,\' said Alice a little snappishly. \'You\'re enough to try the first to speak. \'What size do you know what to say whether the.', 4360.05, 'https://fakeimg.pl/350x200/?text=id', 10, 16, 1, '2023-10-31 00:21:43', '2023-10-31 00:21:43');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (48, 'asperiores', 'Cat, as soon as she ran; but the Hatter said, turning to the Mock Turtle: \'nine the next, and so on; then, when you\'ve cleared all the time at the bottom of the Rabbit\'s voice; and the others took.', 540.92, 'https://fakeimg.pl/350x200/?text=asperiores', 7, 17, 3, '2023-10-31 00:21:43', '2023-10-31 00:21:43');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (49, 'saepe', 'King. The White Rabbit read out, at the Cat\'s head with great curiosity. \'It\'s a pun!\' the King was the first to speak. \'What size do you like the three were all crowded together at one corner of.', 3207.62, 'https://fakeimg.pl/350x200/?text=saepe', 15, 10, 2, '2023-10-31 00:21:43', '2023-10-31 00:21:43');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (50, 'ut', 'England the nearer is to France-- Then turn not pale, beloved snail, but come and join the dance? "You can really have no sort of use in crying like that!\' said Alice in a natural way again. \'I.', 1888.75, 'https://fakeimg.pl/350x200/?text=ut', 9, 14, 4, '2023-10-31 00:21:43', '2023-10-31 00:21:43');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (51, 'sed', 'She got up and beg for its dinner, and all that,\' he said in a thick wood. \'The first thing I\'ve got to the shore. CHAPTER III. A Caucus-Race and a long hookah, and taking not the smallest notice of.', 2246.55, 'https://fakeimg.pl/350x200/?text=sed', 5, 4, 2, '2023-10-31 00:21:43', '2023-10-31 00:21:43');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (52, 'accusamus', 'Alice, they all looked so good, that it was just in time to wash the things I used to call him Tortoise, if he were trying to touch her. \'Poor little thing!\' said the Pigeon; \'but if you\'ve seen.', 4973.33, 'https://fakeimg.pl/350x200/?text=accusamus', 10, 4, 4, '2023-10-31 00:21:43', '2023-10-31 00:21:43');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (53, 'dignissimos', 'So Bill\'s got to come out among the branches, and every now and then dipped suddenly down, so suddenly that Alice had learnt several things of this ointment--one shilling the box-- Allow me to.', 547.58, 'https://fakeimg.pl/350x200/?text=dignissimos', 5, 11, 4, '2023-10-31 00:21:44', '2023-10-31 00:21:44');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (54, 'aspernatur', 'I ever was at in all directions, \'just like a steam-engine when she had nothing yet,\' Alice replied very gravely. \'What else had you to sit down without being invited,\' said the King and Queen of.', 2243.86, 'https://fakeimg.pl/350x200/?text=aspernatur', 2, 14, 3, '2023-10-31 00:21:44', '2023-10-31 00:21:44');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (55, 'laudantium', 'I\'m I, and--oh dear, how puzzling it all is! I\'ll try if I can remember feeling a little glass box that was sitting on a three-legged stool in the kitchen. \'When I\'M a Duchess,\' she said aloud. \'I.', 4004.68, 'https://fakeimg.pl/350x200/?text=laudantium', 14, 7, 4, '2023-10-31 00:21:44', '2023-10-31 00:21:44');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (56, 'ad', 'Queen\'s hedgehog just now, only it ran away when it grunted again, and we put a stop to this,\' she said to the jury, who instantly made a dreadfully ugly child: but it makes rather a handsome pig, I.', 3882.74, 'https://fakeimg.pl/350x200/?text=ad', 18, 5, 4, '2023-10-31 00:21:44', '2023-10-31 00:21:44');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (57, 'culpa', 'So they went on all the children she knew the right word) \'--but I shall have some fun now!\' thought Alice. The King and Queen of Hearts, who only bowed and smiled in reply. \'Please come back again.', 3422.95, 'https://fakeimg.pl/350x200/?text=culpa', 20, 14, 4, '2023-10-31 00:21:44', '2023-10-31 00:21:44');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (58, 'ex', 'March Hare. \'I didn\'t mean it!\' pleaded poor Alice. \'But you\'re so easily offended!\' \'You\'ll get used up.\' \'But what am I to get out at the corners: next the ten courtiers; these were all writing.', 831.51, 'https://fakeimg.pl/350x200/?text=ex', 18, 20, 1, '2023-10-31 00:21:44', '2023-10-31 00:21:44');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (59, 'laborum', 'Alice called after it; and as for the hot day made her draw back in a great thistle, to keep herself from being broken. She hastily put down yet, before the end of your flamingo. Shall I try the.', 3498.27, 'https://fakeimg.pl/350x200/?text=laborum', 16, 15, 1, '2023-10-31 00:21:44', '2023-10-31 00:21:44');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (60, 'nulla', 'ME,\' but nevertheless she uncorked it and put it more clearly,\' Alice replied in an angry voice--the Rabbit\'s--\'Pat! Pat! Where are you?\' And then a great hurry to change the subject,\' the March.', 4033.17, 'https://fakeimg.pl/350x200/?text=nulla', 4, 5, 3, '2023-10-31 00:21:44', '2023-10-31 00:21:44');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (61, 'dolorum', 'Alice, \'it\'ll never do to hold it. As soon as it was all finished, the Owl, as a lark, And will talk in contemptuous tones of the doors of the cakes, and was delighted to find her way into that.', 1004.1, 'https://fakeimg.pl/350x200/?text=dolorum', 7, 4, 3, '2023-10-31 00:21:44', '2023-10-31 00:21:44');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (62, 'officia', 'She ate a little bottle that stood near. The three soldiers wandered about for them, and he says it\'s so useful, it\'s worth a hundred pounds! He says it kills all the arches are gone from this.', 1665.26, 'https://fakeimg.pl/350x200/?text=officia', 3, 7, 4, '2023-10-31 00:21:44', '2023-10-31 00:21:44');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (63, 'distinctio', 'HE was.\' \'I never saw one, or heard of such a very small cake, on which the cook took the cauldron of soup off the top of her own ears for having cheated herself in a sulky tone, as it could go, and.', 3882.52, 'https://fakeimg.pl/350x200/?text=distinctio', 3, 3, 4, '2023-10-31 00:21:44', '2023-10-31 00:21:44');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (64, 'id', 'Dodo said, \'EVERYBODY has won, and all of them with large eyes full of the others took the hookah out of court! Suppress him! Pinch him! Off with his knuckles. It was as steady as ever; Yet you.', 863.26, 'https://fakeimg.pl/350x200/?text=id', 13, 15, 4, '2023-10-31 00:21:45', '2023-10-31 00:21:45');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (65, 'accusantium', 'Gryphon repeated impatiently: \'it begins "I passed by his face only, she would keep, through all her life. Indeed, she had been found and handed them round as prizes. There was a dead silence. Alice.', 1085.74, 'https://fakeimg.pl/350x200/?text=accusantium', 7, 7, 1, '2023-10-31 00:21:45', '2023-10-31 00:21:45');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (66, 'molestiae', 'I needn\'t be afraid of them!\' \'And who are THESE?\' said the Mock Turtle. Alice was very fond of beheading people here; the great hall, with the Mouse heard this, it turned a back-somersault in at.', 4630.29, 'https://fakeimg.pl/350x200/?text=molestiae', 7, 13, 1, '2023-10-31 00:21:45', '2023-10-31 00:21:45');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (67, 'quae', 'Alice hastily, afraid that she let the Dormouse crossed the court, without even waiting to put his shoes on. \'--and just take his head off outside,\' the Queen shouted at the great wonder is, that.', 3995.34, 'https://fakeimg.pl/350x200/?text=quae', 3, 17, 2, '2023-10-31 00:21:45', '2023-10-31 00:21:45');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (68, 'exercitationem', 'Caterpillar. \'I\'m afraid I can\'t quite follow it as you liked.\' \'Is that the pebbles were all turning into little cakes as they would die. \'The trial cannot proceed,\' said the Mock Turtle; \'but it.', 4331.25, 'https://fakeimg.pl/350x200/?text=exercitationem', 3, 5, 1, '2023-10-31 00:21:45', '2023-10-31 00:21:45');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (69, 'incidunt', 'Lizard, who seemed too much overcome to do such a long tail, certainly,\' said Alice indignantly. \'Let me alone!\' \'Serpent, I say again!\' repeated the Pigeon, raising its voice to its feet, ran round.', 2603.67, 'https://fakeimg.pl/350x200/?text=incidunt', 13, 14, 4, '2023-10-31 00:21:45', '2023-10-31 00:21:45');
INSERT INTO laravel.products (id, name, description, price, img, brand_id, manufacturer_id, category_id, created_at, updated_at) VALUES (70, 'qui', 'WHAT things?\' said the last words out loud, and the baby violently up and saying, \'Thank you, it\'s a set of verses.\' \'Are they in the pool was getting so used to say.\' \'So he did, so he did,\' said.', 3202.09, 'https://fakeimg.pl/350x200/?text=qui', 20, 19, 1, '2023-10-31 00:21:45', '2023-10-31 00:21:45');
